theme: minima
title: GitHub Pages
author: Myo Thet
email: mr.myothet@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  GitHub Pages with Jekyll. 
  First week at GitHub Path. 
  Learn and Practise everyday.

# social links
twitter_username: mrmyothet
github_username:  mrmyothet

show_excerpts: false # set to false to remove excerpts on the homepage

---
title: "lessons-from-the-longest-study-on-happiness"
date: 2020-05-11
---
