theme: minima
title: GitHub Pages
author: Myo Thet
email: mr.myothet@gmail.com
description: > Genius is one percent inspiration and ninety-nine percent perspiration.  
**Thomas Edison**

* inspiration - brilliant idea  
* perspiration - the process of sweating  

> Great accomplishments depend not so much on ingenuity as on hard work.

# social links
twitter_username: mrmyothet
github_username:  mrmyothet

show_excerpts: false # set to false to remove excerpts on the homepage

---
title: "lessons-from-the-longest-study-on-happiness"
date: 2020-05-11
---
title: "get-more-work-done-in-a-day"
date: 2020-05-12
---
title: "10-arguments-for-deleting-your-social-media-accounts.md"
date: 2020-05-13
---
title: "the-whole-body-yes.md"
date: 2020-05-14
---
